app = "octobox-9a4bdbf5c73f731f"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[env]
  RAILS_ENV = "production"
  RACK_ENV = "production"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = "true"
  OCTOBOX_BACKGROUND_JOBS_ENABLED = "true"
  OCTOBOX_SIDEKIQ_SCHEDULE_ENABLED = "true"
  FETCH_SUBJECT = "true"
  MINIMUM_REFRESH_INTERVAL = "5"
  GITHUB_SCOPE = "notifications,repo,read:org"
  RESTRICTED_ACCESS_ENABLED = "1"
  GITHUB_ORGANIZATION_ID = "42190284"
  PORT = "3000"
  BINDING = "0.0.0.0"
  WEB_HOST = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "bundle exec rake db:migrate"
